In [315]:
import pandas as pd
df = pd.read_csv('D:\Python\TekWorks\Week_8\customer_churn.csv')
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_13820\4099932140.py:2: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('D:\Python\TekWorks\Week_8\customer_churn.csv')

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1

In [316]:
df.isnull().sum()

age                       0
income                   49
credit_score             50
transactions_month        0
avg_purchase_value       50
days_since_last_login     0
tenure_months             0
num_products              0
gender                    0
region                    0
churn                     0
dtype: int64

In [317]:
df['income'] = df['income'].fillna(df['income'].mode()[0])

In [318]:
df['credit_score'] = df['credit_score'].fillna(df['credit_score'].mean())

In [319]:
df['avg_purchase_value'] = df['avg_purchase_value'].fillna(df['avg_purchase_value'].mean())

In [320]:
df.isnull().sum()

age                      0
income                   0
credit_score             0
transactions_month       0
avg_purchase_value       0
days_since_last_login    0
tenure_months            0
num_products             0
gender                   0
region                   0
churn                    0
dtype: int64

In [321]:
df.describe()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,43.81900,65129.822491,651.422837,29.842000,119.301574,182.155000,60.394000,3.129000,0.517000
std,14.99103,53608.239431,66.541556,5.453511,38.614948,104.205824,34.163166,1.410088,0.499961
min,18.00000,7271.860691,444.172796,15.000000,-7.068153,0.000000,1.000000,1.000000,0.000000
25%,31.00000,41512.194193,608.123302,26.000000,95.676308,88.000000,31.000000,2.000000,0.000000
50%,44.00000,52559.612454,651.422837,30.000000,119.301574,184.000000,61.000000,3.000000,1.000000
75%,56.00000,63946.995415,695.626893,33.000000,144.968351,273.250000,89.250000,4.000000,1.000000
max,69.00000,254852.478291,873.517530,49.000000,244.516408,364.000000,119.000000,5.000000,1.000000

In [322]:
q1 = df['income'].quantile(0.80)
q2 = df['income'].quantile(0.20)
df['income'] = df['income'].clip(lower=q2,upper=q1)

In [323]:
q1 = df['avg_purchase_value'].quantile(0.80)
q2 = df['avg_purchase_value'].quantile(0.20)
df['avg_purchase_value'] = df['avg_purchase_value'].clip(lower=q2,upper=q1)

In [324]:
q1 = df['days_since_last_login'].quantile(0.80)
q2 = df['days_since_last_login'].quantile(0.20)
df['days_since_last_login'] = df['days_since_last_login'].clip(lower=q2,upper=q1)

In [325]:
df.describe()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,43.81900,52928.877623,651.422837,29.842000,119.278804,180.834000,60.394000,3.129000,0.517000
std,14.99103,10621.419573,66.541556,5.453511,23.837442,84.441001,34.163166,1.410088,0.499961
min,18.00000,39618.387568,444.172796,15.000000,87.105288,72.000000,1.000000,1.000000,0.000000
25%,31.00000,41512.194193,608.123302,26.000000,95.676308,88.000000,31.000000,2.000000,0.000000
50%,44.00000,52559.612454,651.422837,30.000000,119.301574,184.000000,61.000000,3.000000,1.000000
75%,56.00000,63946.995415,695.626893,33.000000,144.968351,273.250000,89.250000,4.000000,1.000000
max,69.00000,67521.271511,873.517530,49.000000,150.080446,288.000000,119.000000,5.000000,1.000000

In [326]:
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,67521.271511,770.887470,29,87.105288,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,39618.387568,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,39618.387568,715.281358,29,150.080446,76,110,2,Male,South,0
4,60,40301.406736,651.422837,27,115.391031,168,99,2,Male,East,1

In [327]:
df['gender'] = df['gender'].replace({'Male':0,'Female':1})

C:\Users\vinee\AppData\Local\Temp\ipykernel_13820\35551863.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace({'Male':0,'Female':1})

In [328]:
df.region.unique()

array(['South', 'East', 'North', 'West'], dtype=object)

In [329]:
df['region'] = df['region'].replace({'North':0,'South':1,'East':2,'West':3})

C:\Users\vinee\AppData\Local\Temp\ipykernel_13820\1460139057.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['region'] = df['region'].replace({'North':0,'South':1,'East':2,'West':3})

In [330]:
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,67521.271511,770.887470,29,87.105288,143,90,1,0,1,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,1,2,1
2,46,39618.387568,665.727931,36,114.993023,155,88,3,0,0,1
3,32,39618.387568,715.281358,29,150.080446,76,110,2,0,1,0
4,60,40301.406736,651.422837,27,115.391031,168,99,2,0,2,1

In [331]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
high_scale = ['income', 'credit_score', 'avg_purchase_value']
df[high_scale] = pd.DataFrame(scaler.fit_transform(df[high_scale]), columns=high_scale, index=df.index)

In [332]:
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,1.000000,0.760961,29,0.000000,143,90,1,0,1,1
1,69,0.481440,0.414242,41,0.743762,72,96,4,1,2,1
2,46,0.000000,0.516031,36,0.442837,155,88,3,0,0,1
3,32,0.000000,0.631447,29,1.000000,76,110,2,0,1,0
4,60,0.024478,0.482712,27,0.449157,168,99,2,0,2,1

In [333]:
df.isnull().sum()

age                      0
income                   0
credit_score             0
transactions_month       0
avg_purchase_value       0
days_since_last_login    0
tenure_months            0
num_products             0
gender                   0
region                   0
churn                    0
dtype: int64

In [334]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [335]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [336]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

d:\Python\TekWorks\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [337]:
y_pred = lr.predict(x_test)

In [340]:
from sklearn.metrics import accuracy_score , precision_score , confusion_matrix
accuracy_score(y_pred,y_test)*100

55.00000000000001

In [339]:
confusion_matrix(y_pred,y_test)

array([[45, 31],
       [59, 65]])