In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.read_csv('D:\Python\TekWorks\Week_5\census.csv')
df = pd.DataFrame(a)
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_9756\3351979301.py:1: SyntaxWarning: invalid escape sequence '\P'
  a = pd.read_csv('D:\Python\TekWorks\Week_5\census.csv')

,Age,Eduation,Marital_Status,Gender,Tax_Filing_Status,Income,Parents_Status,Country_of_Birth,Nativity status,Weeks_worked
0,73,Highschoolgraduate,Widowed,Female,Nonfiler,1700.09,Notinuniverse,United-States,Native-BornintheUnitedStates,0
1,58,Somecollegebutnodegree,Divorced,Male,Headofhousehold,1053.55,Notinuniverse,United-States,Native-BornintheUnitedStates,52
2,18,10thgrade,Nevermarried,Female,Nonfiler,991.95,Notinuniverse,Vietnam,Foreignborn-NotacitizenofUS,0
3,9,Children,Nevermarried,Female,Nonfiler,1758.14,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
4,10,Children,Nevermarried,Female,Nonfiler,1069.16,Bothparentspresent,United-States,Native-BornintheUnitedStates,0

In [3]:
df.shape

(2000, 10)

In [5]:
df.isnull().sum()

Age                  0
Eduation             0
Marital_Status       0
Gender               0
Tax_Filing_Status    0
Income               0
Parents_Status       0
Country_of_Birth     0
 Nativity status     0
Weeks_worked         0
dtype: int64

In [6]:
df.describe()

               Age       Income  Weeks_worked
count  2000.000000  2000.000000   2000.000000
mean     34.069000  1728.261635     24.897000
std      21.358332   985.670963     24.450119
min       0.000000    60.710000      0.000000
25%      16.000000  1059.292500      0.000000
50%      33.000000  1609.305000     21.500000
75%      48.000000  2179.840000     52.000000
max      90.000000  8559.640000     52.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2000 non-null   int64
 1   Eduation           2000 non-null   str
 2   Marital_Status     2000 non-null   str
 3   Gender             2000 non-null   str
 4   Tax_Filing_Status  2000 non-null   str
 5   Income             2000 non-null   float64
 6   Parents_Status     2000 non-null   str
 7   Country_of_Birth   2000 non-null   str
 8    Nativity status   2000 non-null   str
 9   Weeks_worked       2000 non-null   int64
dtypes: float64(1), int64(2), str(7)
memory usage: 156.4 KB

In [8]:
df.nunique()

Age                    91
Eduation               17
Marital_Status          7
Gender                  2
Tax_Filing_Status       6
Income               1981
Parents_Status          5
Country_of_Birth       37
 Nativity status        5
Weeks_worked           48
dtype: int64

In [12]:
df['Country_of_Birth'].unique().value_counts()

United-States               1
Vietnam                     1
?                           1
Columbia                    1
Mexico                      1
Peru                        1
Cuba                        1
Philippines                 1
Dominican-Republic          1
El-Salvador                 1
Canada                      1
Scotland                    1
Portugal                    1
Guatemala                   1
Ecuador                     1
Germany                     1
Outlying-US(GuamUSVIetc)    1
Puerto-Rico                 1
Italy                       1
China                       1
Poland                      1
Nicaragua                   1
Taiwan                      1
England                     1
Ireland                     1
SouthKorea                  1
Trinadad&Tobago             1
Jamaica                     1
Honduras                    1
Iran                        1
Hungary                     1
France                      1
Cambodia                    1
India                       1
HongKong                    1
Japan                       1
Haiti                       1
Name: count, dtype: int64

In [13]:
df.columns

Index(['Age', 'Eduation', 'Marital_Status', 'Gender', 'Tax_Filing_Status',
       'Income', 'Parents_Status', 'Country_of_Birth', ' Nativity status',
       'Weeks_worked'],
      dtype='str')

In [15]:
df.rename(columns={'Eduation':'Education','Country_of_Birth':'Birth_Place'}).head()

,Age,Education,Marital_Status,Gender,Tax_Filing_Status,Income,Parents_Status,Birth_Place,Nativity status,Weeks_worked
0,73,Highschoolgraduate,Widowed,Female,Nonfiler,1700.09,Notinuniverse,United-States,Native-BornintheUnitedStates,0
1,58,Somecollegebutnodegree,Divorced,Male,Headofhousehold,1053.55,Notinuniverse,United-States,Native-BornintheUnitedStates,52
2,18,10thgrade,Nevermarried,Female,Nonfiler,991.95,Notinuniverse,Vietnam,Foreignborn-NotacitizenofUS,0
3,9,Children,Nevermarried,Female,Nonfiler,1758.14,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
4,10,Children,Nevermarried,Female,Nonfiler,1069.16,Bothparentspresent,United-States,Native-BornintheUnitedStates,0