In [4]:
import pandas as pd
df = pd.read_csv('D:\Python\TekWorks\Week_9\decision_tree_dataset.csv')
df.sample(10)

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_18808\1111053896.py:2: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('D:\Python\TekWorks\Week_9\decision_tree_dataset.csv')

,age,income,credit_score,city,gender,purchases,loan_amount,approved
341,59,41348.430041,641.731931,Mumbai,Male,1,229164.918188,0
73,46,39925.649481,568.074214,Bangalore,Female,3,59657.211774,0
594,48,70853.113235,673.007076,Delhi,Male,2,96724.622441,0
494,42,44859.686089,610.824185,Mumbai,Male,2,371440.564367,0
696,44,31613.515055,689.241597,Hyderabad,Male,4,NaN,0
62,64,70181.300692,583.185591,Bangalore,Female,0,264563.713329,0
576,59,67539.433857,NaN,Mumbai,Female,4,151419.086873,1
1033,45,55610.848548,648.791105,Bangalore,Male,2,252836.796188,0
121,40,46946.294598,708.441298,Hyderabad,Male,4,231647.906781,1
963,18,62455.037248,567.240978,Delhi,Female,3,NaN,0

In [5]:
df.isnull().sum()

age               0
income          103
credit_score    104
city              0
gender            0
purchases         0
loan_amount     103
approved          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1050 non-null   int64
 1   income        947 non-null    float64
 2   credit_score  946 non-null    float64
 3   city          1050 non-null   object
 4   gender        1050 non-null   object
 5   purchases     1050 non-null   int64
 6   loan_amount   947 non-null    float64
 7   approved      1050 non-null   int64
dtypes: float64(3), int64(3), object(2)
memory usage: 65.8+ KB

In [25]:
df['income'].fillna(df['income'].median(),inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_18808\732058309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['income'].fillna(df['income'].median(),inplace=True)

In [26]:
df['credit_score'].fillna(df['credit_score'].median(),inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_18808\1478945443.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['credit_score'].fillna(df['credit_score'].median(),inplace=True)

In [27]:
df['loan_amount'].fillna(df['loan_amount'].median(),inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_18808\4204518281.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['loan_amount'].fillna(df['loan_amount'].median(),inplace=True)

In [28]:
df.isnull().sum()

age             0
income          0
credit_score    0
city            0
gender          0
purchases       0
loan_amount     0
approved        0
dtype: int64

In [29]:
q1 = df['loan_amount'].quantile(0.20)
q2 = df['loan_amount'].quantile(0.80)
df['loan_amount'] = df['loan_amount'].clip(lower=q1,upper=q2)

In [30]:
q1 = df['income'].quantile(0.20)
q2 = df['income'].quantile(0.80)
df['income'] = df['income'].clip(lower=q1,upper=q2)

In [31]:
df.describe()

,age,income,credit_score,gender,purchases,loan_amount,approved
count,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000
mean,43.737143,51513.625821,651.605495,0.485714,2.934286,199791.752093,0.303810
std,15.021797,8557.645402,95.071248,0.500034,1.603281,51495.124783,0.460121
min,18.000000,39924.529127,348.048784,0.000000,0.000000,131683.573550,0.000000
25%,31.000000,41799.420230,594.897650,0.000000,2.000000,144201.301913,0.000000
50%,44.000000,52948.069597,651.605495,0.000000,3.000000,208247.347300,0.000000
75%,56.000000,59446.374423,711.669725,1.000000,4.000000,253270.599948,1.000000
max,69.000000,62578.653281,969.310757,1.000000,9.000000,269143.203164,1.000000

In [32]:
df.columns

Index(['age', 'income', 'credit_score', 'city', 'gender', 'purchases',
       'loan_amount', 'approved'],
      dtype='object')

In [33]:
df.gender.unique()

array([0, 1])

In [34]:
df.gender.replace({'Female':0,'Male':1},inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_18808\1321743168.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.gender.replace({'Female':0,'Male':1},inplace=True)

In [35]:
df = pd.get_dummies(df,columns=['city'],drop_first=True)

In [100]:
df.shape

(1050, 10)

In [43]:
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report , confusion_matrix

In [44]:
def model(df):
    X = df.iloc[: , :-1]
    y = df.iloc[: , -1]
    X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2)
    sc = StandardScaler()
    X_train_scaled = sc.fit_transform(X_train)
    X_test_scaled = sc.transform (X_test)
    lg = DecisionTreeClassifier()
    lg.fit(X_train_scaled , y_train)
    lg_preds = lg.predict(X_test_scaled)
    print(classification_report(y_test , lg_preds))
    cm = confusion_matrix(y_test , lg_preds)
    print(cm)

In [99]:
model(df)

              precision    recall  f1-score   support

       False       0.88      0.89      0.89       164
        True       0.60      0.59      0.59        46

    accuracy                           0.82       210
   macro avg       0.74      0.74      0.74       210
weighted avg       0.82      0.82      0.82       210

[[146  18]
 [ 19  27]]