In [2]:
import pandas as pd
a = pd.read_csv('D:\Python\TekWorks\Week_3\dataset.csv')
df = pd.DataFrame(a)
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_23176\2184959295.py:2: SyntaxWarning: invalid escape sequence '\P'
  a = pd.read_csv('D:\Python\TekWorks\Week_3\dataset.csv')

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
#CREATING DICTIONARY AND CONVERTING INTO DATAFRAME
data = {
    'Name' : ['A','B','C'],
    'Gender' : ['M','M','F'],
    'Age' : [10,11,11]
}

'''array_4D=[[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]]
df_array = pd.DataFrame(array_4d,columns=['Col_1','Col_2'])'''

a = pd.DataFrame(data)
print(type(a))
print(a.head())
#print(type(array_4d))
#print(df_array)
a.rename(columns={'Name' : 'NAME',
    'Gender' : 'Sex',
    'Age' : 'Levels'
},inplace=True)
a

<class 'pandas.DataFrame'>
  Name Gender  Age
0    A      M   10
1    B      M   11
2    C      F   11

  NAME Sex  Levels
0    A   M      10
1    B   M      11
2    C   F      11

In [4]:
array_4D=[[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]]
df_array = pd.DataFrame(array_4D,columns=['Col_1','Col_2'])
print(df_array)

                 Col_1                 Col_2
0     [[1, 2], [3, 4]]      [[5, 6], [7, 8]]
1  [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [5]:
#PERFORMING VARIOUS OPERATIONS ON GIVEN DATASET
a = pd.read_csv('D:\Python\TekWorks\Week_3\dataset.csv')
df = pd.DataFrame(a)
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_23176\2852820925.py:2: SyntaxWarning: invalid escape sequence '\P'
  a = pd.read_csv('D:\Python\TekWorks\Week_3\dataset.csv')

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [7]:
df[['age','sex']].tail()

     age  sex
298   57    0
299   45    1
300   68    1
301   57    1
302   57    0

In [8]:
df.iat[0,2]

np.int64(3)

In [9]:
df.query("age > 50 and sex == 1").tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0

In [10]:
df.isnull().sum() #counts missing per column

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
df.sort_values(by='age',ascending=True).head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
227,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0

In [12]:
df.groupby(['sex']).mean()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
sex,,,,,,,,,,,,,
0,55.677083,1.041667,133.083333,261.302083,0.12500,0.572917,151.125000,0.229167,0.876042,1.427083,0.552083,2.125000,0.750000
1,53.758454,0.932367,130.946860,239.289855,0.15942,0.507246,148.961353,0.371981,1.115459,1.386473,0.811594,2.400966,0.449275

In [13]:
df.groupby('sex')['age'].max()

sex
0    76
1    77
Name: age, dtype: int64

In [14]:
df.iloc[1,2]
df.loc[2,'age']

np.int64(41)

In [15]:
df['chol'] = df['chol'].astype('float16')
df['chol'].head()

d:\Python\TekWorks\.venv\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

0    233.0
1    250.0
2    204.0
3    236.0
4    354.0
Name: chol, dtype: float16

In [16]:
s = df.query("age > 20 and age < 60")
print(len(s))

213

In [17]:
df['chol'].head()

d:\Python\TekWorks\.venv\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

0    233.0
1    250.0
2    204.0
3    236.0
4    354.0
Name: chol, dtype: float16

In [18]:
df['chol_level'] = df['chol'] > 200
df['chol_level'].head()

0    True
1    True
2    True
3    True
4    True
Name: chol_level, dtype: bool

In [ ]:
employees = pd.DataFrame({
"EmpID": [1, 2, 3],
"Name": ["Alice", "Bob", "Charlie"],
"DeptID": [10, 20, 30]
})
departments = pd.DataFrame({
"DeptID": [10, 20, 40],
"DeptName": ["HR", "Engineering", "Marketing"]
})

pd.merge(employees,departments,on='DeptID')

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing