In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_csv("D:\Python\TekWorks\Week_3\Dataset_1.csv")
df = pd.DataFrame(a)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_23392\3844467398.py:1: SyntaxWarning: invalid escape sequence '\P'
  a = pd.read_csv("D:\Python\TekWorks\Week_3\Dataset_1.csv")

In [3]:
df.head()

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,yes

In [4]:
#1
df['order_amount'] = df['order_amount'].replace('₹999',999,inplace=True)
df['order_amount'] = df['order_amount'].astype('float')
df['order_amount'].unique()

C:\Users\vinee\AppData\Local\Temp\ipykernel_23392\2625200018.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['order_amount'] = df['order_amount'].replace('₹999',999,inplace=True)

array([ 250.5 , 1200.  ,     nan, 3500.75,  999.  ,  499.99])

In [5]:

df['is_delivered'] = df['is_delivered'].replace('yes','True',inplace=True)
df['is_delivered'] = df['is_delivered'].replace('no','False',inplace=True)
df['is_delivered'].unique()

C:\Users\vinee\AppData\Local\Temp\ipykernel_23392\34912946.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['is_delivered'] = df['is_delivered'].replace('yes','True',inplace=True)
C:\Users\vinee\AppData\Local\Temp\ipykernel_23392\34912946.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['is_delivered'] = df['is_delivered'].replace('no','False',inplace=True)

<StringArray>
['True', 'False', nan]
Length: 3, dtype: str

In [6]:
df.query("order_amount.isna() and is_delivered == 'True'").head()

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,True
14,ORD1014,CUST14,25.0,NaN,2023/03/10,upi,DELHI,5,True
17,NaN,NaN,-3.0,NaN,15/02/2023,upi,Hyderabad,NaN,True
29,NaN,user_29,NaN,NaN,NaN,Debit Card,DELHI,7,True
38,NaN,CUST38,35.0,NaN,15/02/2023,CARD,NaN,1,True

In [7]:
#2
df['order_date'] = df['order_date'].replace('invalid',np.nan)
df['order_date'].unique()

<StringArray>
['2023-01-15', '2023/03/10', nan, '15/02/2023']
Length: 4, dtype: str

In [8]:

df['order_date'] = pd.to_datetime(df['order_date'],format='mixed',errors='coerce',dayfirst=True)

In [9]:
df['delivery_days'] =df['delivery_days'].replace('three','3',inplace=True)
df['delivery_days'] =df['delivery_days'].astype('float64')

C:\Users\vinee\AppData\Local\Temp\ipykernel_23392\1739790301.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['delivery_days'] =df['delivery_days'].replace('three','3',inplace=True)

In [10]:
df[(df['delivery_days']<0) & (df['order_date'].notna())].head()

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
9,NaN,user_9,NaN,NaN,2023-10-03,UPI,Delhi,-1.0,False
47,NaN,user_47,25.0,NaN,2023-10-03,Cash,Mumbai,-1.0,NaN
49,ORD1049,CUST49,120.0,3500.75,2023-02-15,NaN,Hyderabad,-1.0,False
51,ORD1051,user_51,50.0,499.99,2023-02-15,CARD,Delhi,-1.0,NaN
57,ORD1057,CUST57,35.0,NaN,2023-02-15,Credit Card,Mumbai,-1.0,True

In [11]:
#4
df.customer_age.unique()

array([ nan,  18.,  35.,  -3., 120.,  65.,  25.,  50.])

In [12]:
a = df.order_amount.median()
a

np.float64(999.0)

In [13]:
df.shape

(1000, 9)

In [14]:
df[ ( (df['customer_age'] < 0 ) | ( df['customer_age'] >100) ) & ( df['order_amount'] > a)  ].head()

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,3.0,True
34,ORD1034,NaN,120.0,3500.75,2023-10-03,Debit Card,Hyderabad,7.0,True
49,ORD1049,CUST49,120.0,3500.75,2023-02-15,NaN,Hyderabad,-1.0,False
53,NaN,user_53,120.0,3500.75,NaT,Debit Card,Hyderabad,NaN,NaN
59,NaN,NaN,-3.0,3500.75,2023-02-15,Cash,Bangalore,3.0,False

In [15]:
#5
dupli = df.groupby('customer_id')['city'].nunique()
dupli.shape

(489,)

In [16]:
a = dupli[dupli>=1]
a

customer_id
CUST108     1
CUST11      1
CUST111     1
CUST117     1
CUST119     1
           ..
user_959    1
user_97     1
user_977    1
user_995    1
user_997    1
Name: city, Length: 413, dtype: int64

In [17]:
#6
df['order_place_status']=(df['delivery_days'].isna()) & (df['is_delivered']=='True')
df.sample(5)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered,order_place_status
11,NaN,CUST11,18.0,3500.75,NaT,Cash,Mumbai,-1.0,False,False
639,NaN,CUST639,-3.0,499.99,2023-01-15,Cash,DELHI,-1.0,False,False
448,ORD1448,CUST448,50.0,NaN,NaT,upi,Bangalore,7.0,True,False
372,ORD1372,NaN,35.0,1200.00,2023-02-15,Credit Card,mumbai,-1.0,False,False
841,ORD1841,user_841,65.0,999.00,NaT,Credit Card,Delhi,NaN,NaN,False

In [18]:
#7
s = df.groupby('payment_mode')['order_amount'].count()
s.groupby('payment_mode').mean()

payment_mode
CARD           118.0
Cash           117.0
Credit Card     83.0
Debit Card     102.0
UPI            106.0
upi             95.0
Name: order_amount, dtype: float64