1. what is svm?
    svm is used for complex data compression,classification problem and binary classification
    examples are spam vs not spam,cat vs dog etc.
2. problem with logistic regression?
    logistic reg works well when data is linearly seperable but what if data is complex,classes overlap,decision boundary is not right this is where svm becomes powerful
3. what are parameters?
    values which learn from data given
4. what are hyperparamaters?
    values which doesnt learn from any data they are input paramters which are directly related to model.

Mathematical

eq of hyperplane :
w.x + b = 0 
w = weights
x =input 
b= bias / intercept 
prediction rule : 
if w.x + b >= 0 --> class 1 
else w.x + b <0 --> class 0

In [158]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC , SVR
from sklearn.metrics import classification_report , accuracy_score , confusion_matrix ,r2_score
from sklearn.preprocessing import StandardScaler

In [159]:

df = pd.read_csv("C:\\Users\\vinee\Downloads\\heart-2.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [160]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [161]:
def model(df):
    X = df.iloc[: , :-1]
    y = df.iloc[: , -1]
    X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2)
    sc = StandardScaler()
    X_train_scaled = sc.fit_transform(X_train)
    X_test_scaled = sc.transform (X_test)
    #lg = ()
    #lg.fit(X_train , y_train)
    svm = SVC(kernel='linear',probability=True,C=1,max_iter=100,break_ties=True,random_state=42)
    svm.fit(X_train_scaled,y_train)
    lg_preds = svm.predict(X_test)
    print(classification_report(y_test , lg_preds))
    cm = confusion_matrix(y_test , lg_preds)
    print(cm)

In [162]:
model(df)

              precision    recall  f1-score   support

           0       0.56      1.00      0.71       114
           1       0.00      0.00      0.00        91

    accuracy                           0.56       205
   macro avg       0.28      0.50      0.36       205
weighted avg       0.31      0.56      0.40       205

[[114   0]
 [ 91   0]]

d:\Softwares\Anacoda\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
d:\Softwares\Anacoda\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(
d:\Softwares\Anacoda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Softwares\Anacoda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Softwares\Anacoda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [163]:
df_reg = pd.read_csv('D:\Python\TekWorks\Week_10\Data.csv')
df_reg.head()

   Feature1  Feature2  Feature3  Feature4  Target
0        63        59      1164        -3      39
1        89        54       977        -2      54
2        73        46       725        -1      88
3        25        52       921         0      70
4        60        60      1222         0      91

In [166]:
df_reg.isna().sum()

Feature1    0
Feature2    0
Feature3    0
Feature4    0
Target      0
dtype: int64

In [190]:
def model(df):
    X = df_reg.iloc[: , :-1]
    y = df_reg.iloc[: , -1]
    X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2)
    sc = StandardScaler()
    X_train_scaled = sc.fit_transform(X_train)
    X_test_scaled = sc.transform (X_test)
    #lg = ()
    #lg.fit(X_train , y_train)
    svm = SVR(kernel='rbf',C=1.0)
    svm.fit(X_train_scaled,y_train)
    lg_preds = svm.predict(X_test)
    r2 = r2_score(y_test,lg_preds)
    print(r2)

In [191]:
model(df_reg)

d:\Softwares\Anacoda\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(

-0.002303098519247815